version: "1.0"
services:
    db:
        image: mysql:8.0
        container_name: flashclub-db
        restart: always
        command: [ "mysqld",
                    "--character-set-server=utf8mb4",
                    "--collation-server=utf8mb4_unicode_ci",
                    "--bind-address=0.0.0.0",
                    "--require_secure_transport=ON",
                    "--ssl-ca=/etc/certs/root-ca.pem",
                    "--ssl-cert=/etc/certs/server-cert.pem",
                    "--ssl-key=/etc/certs/server-key.pem",
                    "--default_authentication_plugin=mysql_native_password" ]
        environment:
          MYSQL_DATABASE: flashclub
          MYSQL_ROOT_PASSWORD: Student2
          MYSQL_PASSWORD: Student1
          MYSQL_USER: flash
        volumes:
          - type: bind
            source: ./storage/db-data
            target: /var/lib/mysql
          - type: bind
            source: ./certs
            target: /etc/certs/
        ports:
          - '8002:3306'