version: "1.0"
services:
    db:
        image: mysql:8.0
        container_name: flashclub-db
        restart: always
        environment:
          MYSQL_DATABASE: flashclub
          MYSQL_ROOT_PASSWORD: Student2
          MYSQL_PASSWORD: Student1
          MYSQL_USER: flash
        volumes:
          - type: bind
            source: ./storage/db-data
            target: /var/lib/mysql
        ports:
          - '8002:3306'