apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  selector: 
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      name: flask
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: killiandel/flasksct:1.0
          ports:
            - containerPort: 3000